CREATE TABLE IF NOT EXISTS "shop_type" (
	"shoptypeid" serial PRIMARY KEY NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_master" (
	"id" serial NOT NULL,
	"userid" serial PRIMARY KEY NOT NULL,
	"fullname" text,
	"mobilenumber" text,
	"isvalidated" boolean,
	"isenabled" boolean,
	"businessname" text,
	"dpname" text,
	"otp" text,
	"appleauthtkn" text,
	"appleAuthTknSecret" text,
	"appleAuthTknUserID" text,
	"appleAuthTknUserName" text,
	"googleAuthTkn" text,
	"googleAuthTknSecret" text,
	"googleAuthTknUserID" text,
	"googleAuthTknUserName" text,
	"loggedInWith" text,
	"postcode" text,
	"address1" text,
	"address2" text,
	"city" text,
	"ageGroup" text,
	"gender" text,
	"appVersion" text,
	"lastActivity" text,
	"createdOn" text,
	"currentSchemeID" integer,
	"currentSchemeName" text,
	"currentSchemeAmount" text,
	"currentSchemePurchaseDate" date,
	"currentSchemeValidityDate" date,
	"userRating" text,
	"pushNotificationToken" text,
	"mobileDevice" text,
	"secureToken" text,
	"thanosID" integer,
	"thanosPassword" text,
	"isAdmin" boolean,
	"cashiertills" integer,
	"paiduser" boolean,
	"usertype" text,
	"interests" text,
	"baselongitude" numeric,
	"baselatitude" numeric,
	"created_at" timestamp,
	"updated_at" timestamp,
	CONSTRAINT "user_master_userid_unique" UNIQUE("userid")
);
